//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int ID_FeedBack { get; set; }
        public Nullable<bool> Likes { get; set; }
        public Nullable<System.DateTime> Cmt_Time { get; set; }
        public string Cmt { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
